### ISSUE TITLE
CSS Issue (3.4.1): Dropdown buttons are not wrapped if the block column becomes too small

### ISSUE THREAD

**Issue by amkdev** [vandres/craft-matrix-extended#14]
`flex-wrap: wrap;` is missing on .buttons.matrix-extended-buttons-DIV

<img width="873" alt="grafik" src="https://github.com/vandres/craft-matrix-extended/assets/5300389/762b9580-1fdd-49a8-a386-1d1e4ce46fb0">

**Comment by vandres** [comment]
Thanks for the report. It's unfortunetly not that easy. For another use case, I prefer this view 

![grafik](https://github.com/vandres/craft-matrix-extended/assets/1436383/753176a1-2d3d-44b2-8c96-3e7e9e45caa7)

over  

![grafik](https://github.com/vandres/craft-matrix-extended/assets/1436383/ff4dd985-45f5-4f20-a698-0a2e89ac5f76)

I might be able to make the "flex-wrap" depending on the `expandUngrouped` setting. Give me a little, to think about it

**Comment by amkdev** [comment]
No hurry. I just noticed it ... it's not so important. :)

**Comment by vandres** [comment]
Release as v3.4.2
