### ISSUE TITLE
Error "unsupported site" on duplicate on multi-site setup

### ISSUE THREAD

**Issue by tibbis** [vandres/craft-matrix-extended#18]
Hi! 

I have two site groups A and B, where everything works fine on site group A but when I try to duplicate matrix blocks or drag and drop on a Site in site group B, it gives me "There was an error duplicating the entry" and the following error on craft debug bar:
 
 on the ajax preview I see error: 
"Request missing required body param"
<img width="1357" alt="Screenshot 2024-10-12 at 23 17 15" src="https://github.com/user-attachments/assets/099aa69f-d982-400c-ac5b-fd0334d87f85">

`craft\errors\UnsupportedSiteException: Attempting to save an element in an unsupported site. in /var/www/html/vendor/craftcms/cms/src/services/Elements.php:3529 Stack trace: #0 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1307): craft\services\Elements->_saveElementInternal() #1 /var/www/html/vendor/vandres/craft-matrix-extended/src/controllers/MatrixExtendedController.php(157): craft\services\Elements->saveElement() #2 /var/www/html/vendor/vandres/craft-matrix-extended/src/controllers/MatrixExtendedController.php(82): vandres\matrixextended\controllers\MatrixExtendedController->cloneEntry() #3 [internal function]: vandres\matrixextended\controllers\MatrixExtendedController->actionDuplicateEntry() #4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction() #8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction() #9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest() #10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #11 /var/www/html/web/index.php(12): yii\base\Application->run() #12 {main} `

I have tried resaving entries and deleting drafts with craft gc command. Not sure what to try next.

**Comment by vandres** [comment]
Hi @tibbis 

Thank you for the report. I will have a look into the issue.

How is that Entry set up? Is it only available in one of the sites? Is the Entry itself only available on one site or the whole Section?

**Comment by tibbis** [comment]
> Hi @tibbis
> 
> Thank you for the report. I will have a look into the issue.
> 
> How is that Entry set up? Is it only available in one of the sites? Is the Entry itself only available on one site or the whole Section?

sections are available on all sites yes!

**Comment by vandres** [comment]
When you create an empty Entry and try duplication there, do you still get that error?

**Comment by vandres** [comment]
All my projects are multi site and I am having trouble reproducing the issue.

**Comment by tibbis** [comment]
do you have several site groups? Yeah same problem with duplicate in same matrix field. 
<img width="1495" alt="Screenshot 2024-10-14 at 13 43 51" src="https://github.com/user-attachments/assets/673c9572-c693-40cd-8600-41a74a91b14c">

**Comment by vandres** [comment]
Could you show me the configuration of that section and the contained Matrix?

**Comment by tibbis** [comment]
> Could you show me the configuration of that section and the contained Matrix?

I just realised it was not due to site groups but just other sites than the **primary site**, so only the primary site works actually. 

Sure: 
<img width="2238" alt="Screenshot 2024-10-14 at 14 39 23" src="https://github.com/user-attachments/assets/c6bcb0b1-4bb6-4145-a02b-99399412e07a">
<img width="2329" alt="Screenshot 2024-10-14 at 14 40 07" src="https://github.com/user-attachments/assets/5499cec9-1efa-4b25-9402-79246dfeb0e3">

**Comment by tibbis** [comment]
seems to be the propagation method on the matrix field that is the issue. are not all options compatible?

**Comment by vandres** [comment]
I can reproduce with the following:

- Matrix is setup to "only save to site, where they are created in"
- Duplicate entry-type in non-primary site

**Comment by vandres** [comment]
@tibbis I released the version 3.5.1. Could you please take a look?

**Comment by tibbis** [comment]
> @tibbis I released the version 3.5.1. Could you please take a look?

Perfect works now! Thanks for fixing it so fast.
