### ISSUE TITLE
Copy controller is only available when `experimentalFeatures` is enabled

### ISSUE THREAD

**Issue by daltonrooney** [vandres/craft-matrix-extended#19]
Hi there, thanks for the plugin! Something like this is very much needed for Craft 5. 😀

I just wanted to suggest some feedback, maybe for clarification in the docs. From the feature list, I understood that "Copy & Paste of Entries" is a standard feature and "Drag and Drop of Entries" is behind the `experimentalFeatures` flag. So I was very confused when I could see the "Copy" feature enabled in the matrix disclosure menu, but receive the error "There was an error copying the entry reference" when I try to use it. 

It was only when I browsed the code a bit that I see that the `CopyEntry()` controller is behind the experimentalFeatures flag. In that case, wouldn't you want to remove it from the disclosure menu as well?

**Comment by vandres** [comment]
You are right, that is a leftover from the past. I think, I will remove the `experimentalFeatures` entirely and hide possibly new features behind separate feature flags . Like `enableDragDrop`.

Thanks for bringing that to my attention!

**Comment by vandres** [comment]
Fixed in 3.5.2

**Comment by daltonrooney** [comment]
Thanks for the quick fix! 👍🏻
