### ISSUE TITLE
Vite configuration conflicting with other Vite dev tools

### ISSUE THREAD

**Issue by daltonrooney** [vandres/craft-matrix-extended#21]
We're running Vite as our primary front-end builder, which means `VITE_PLUGIN_DEVSERVER=1` is always enabled when we're in dev mode. We're running Vite on port 8080 using the `vite.php`config settings like this:

```
return [
    'useDevServer' => App::env('ENVIRONMENT') === 'dev' || App::env('CRAFT_ENVIRONMENT') === 'dev',
    'manifestPath' => '@webroot/dist/manifest.json',
    'devServerPublic' => 'http://localhost:8080/',
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',
    'errorEntry' => '',
    'cacheKeySuffix' => '',
    'devServerInternal' => '',
    'checkDevServer' => false,
    'includeReactRefreshShim' => false,
    'includeModulePreloadShim' => true,
    'criticalPath' => '@webroot/dist/criticalcss',
    'criticalSuffix' =>'_critical.min.css',
];
```

With this configuration, the CP assets for your plugin are not loading correctly. It's not a very big deal, since we don't run the dev server in production, but it was just a bit confusing when trying to config the plugin and it wasn't working.

For [your Vite configuration](https://github.com/vandres/craft-matrix-extended/blob/0b8c06af586ae40efbd55ee56ebb4aeaf597627d/src/web/assets/cp/MatrixExtendedAsset.php#L27), would you consider putting that behind another plugin-specific config flag rather than relying on the `VITE_PLUGIN_DEVSERVER=1` value?

**Comment by vandres** [comment]
I will use a different env var in the next release.
