### ISSUE TITLE
"Add field" position above blocks?

### ISSUE THREAD

**Issue by tibbis** [vandres/craft-matrix-extended#23]
Hi, I have seen examples where the matrix field add field is shown above the blocks. How can I enable this?
  
<img width="1201" alt="Screenshot 2024-10-31 at 13 33 37" src="https://github.com/user-attachments/assets/23f40354-403f-42d5-8940-4f973ff90220">
thanks

**Comment by vandres** [comment]
You should see it as the first option in the disclosure menu. If you have only on entry type available, make sure the update to the latest version.

<img width="1286" alt="grafik" src="https://github.com/user-attachments/assets/2a8cfb61-dc98-4d53-948b-22a1e4ea2483">

**Comment by tibbis** [comment]
Oh I see! So not possible to have it there by default, always have to click in the disclosure menu?

**Comment by vandres** [comment]
Yes. It copies the Neo-style and also allows to place blocks inbetween entry types. Would be bad UX imo, if the whole "add field" element would be repeated in between all entry types
