### ISSUE TITLE
Bug: "Add blocks above" feature adds two matrix blocks

### ISSUE THREAD

**Issue by tibbis** [vandres/craft-matrix-extended#24]
If you use the "add blocks above" feature and then add a block, it will add it two times. 

Craft cms pro 5.5.3
plugin v3.6.1

**Comment by vandres** [comment]
Thanks for the report. I will look into it

**Comment by vandres** [comment]
Can confirm. But only with Craft 5.5.x

**Comment by vandres** [comment]
Fixed in v3.6.2
