### ISSUE TITLE
[Bug]: Copy/paste duplicates and creates new matrix block instead of pasting to block

### ISSUE THREAD

**Issue by tibbis** [vandres/craft-matrix-extended#25]
Using Copy/paste in a matrix block duplicates and creates new matrix block instead of pasting to block (craft 5.5.x).

**Comment by tibbis** [comment]
Video demonstration: 

Using Plugin v3.6.3.

https://github.com/user-attachments/assets/f87888b9-563b-4130-90eb-d7c84af51507

**Comment by vandres** [comment]
That, what you are showing, is the intended behaviour. You can copy any element type and paste it somewhere else in the Matrix (or another supported Matrix). What behaviour would you expect?

**Comment by tibbis** [comment]
Ah okey, I misunderstood the feature, though it would paste the content of the fields to the block. my bad!

**Comment by vandres** [comment]
That might be an interesting feature. But you might be quicker just copying and pasting the element directly.
