### ISSUE TITLE
Delete Buttons appears twice in Block Context Menu

### ISSUE THREAD

**Issue by sandrodunkel** [vandres/craft-matrix-extended#6]
![image](https://github.com/vandres/craft-matrix-extended/assets/102292752/195959cb-fa61-4cd6-ba65-9299249a9612)

**Comment by vandres** [comment]
That is on purpose. Maybe I should make it configurable. I made the extension mostly for my clients, because with all the different entry types, the delete button can be to far below.
![grafik](https://github.com/vandres/craft-matrix-extended/assets/1436383/b576402a-b1d4-4aa8-b7ab-342399f1cefa)

**Comment by sandrodunkel** [comment]
Oh, alrighty then. Makes sense. Config for this would be nice, if not, that's ok too.

**Comment by vandres** [comment]
Implemented in v.3.1.0
